version: '3.8'

services:
  server:
    image: "${ECR_REGISTRY}/inventoryapp-server-stage:${VERSION_TAG:-latest}"
    ports:
      - "3101:3001"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      AWS_S3_BUCKET_NAME: "${AWS_S3_BUCKET_NAME}"

  client:
    image: "${ECR_REGISTRY}/inventoryapp-client-stage:${VERSION_TAG:-latest}"
    ports:
      - "3100:3000"
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}"
