services:
  server:
    build:
      context: . # Build the image from the current directory (where Dockerfile is located)
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001" # Keep backend exposed on 3001
    environment:
      DATABASE_URL: postgresql://kidwalks_db:my_kidwalks@kidwalks-postgres-db.cneus2kmm5hx.us-east-2.rds.amazonaws.com:5432/kidwalks_db

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000" # Serve frontend on port 80 (public access)
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://3.140.15.162:3001

