services:
  server:
    build:
      context: . # Build the image from the current directory (where Dockerfile is located)
      dockerfile: ./server/Dockerfile
    ports:
      - "4000:3001" # Map host port 3000 to container port 3000
    depends_on:
      - db # Ensure the database service starts before the Node.js app
    environment:
      DATABASE_URL: postgresql://db_user:my_password@db:5432/my_database?schema=public # Connection string for Node.js app

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5000:3000"
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://server:3001

  # PostgreSQL database service
  db:
    image: postgres:latest # Use a specific PostgreSQL image
    environment:
      - POSTGRES_DB=my_database # Database name
      - POSTGRES_USER=db_user # Database user
      - POSTGRES_PASSWORD=my_password # Database password
    volumes:
      - db:/var/lib/postgresql/data # Persist database data in a named volume
    ports:
      - 5432:5432

volumes:
  db: # Define the named volume for database data persistence
